namespace GuardeSoftwareAPI.Dtos.Sync
{
    public class SyncClientDto
    {
        public int Id { get; set; }
        public string FullName { get; set; } = string.Empty;
        public decimal? PaymentIdentifier { get; set; }
        public decimal? Balance { get; set; }
        public decimal? CurrentRent { get; set; }
        public decimal? PreviousBalance { get; set; }
        public decimal? PendingSurcharge { get; set; }
        public decimal? InterestAmount { get; set; }
        public string? LastGeneratedMonthYear { get; set; }
        public string? Color { get; set; }
        public bool? Active { get; set; }
        public int? PreferredPaymentMethodId { get; set; }
        // New enriched fields
        public string? NextPaymentDay { get; set; }
        public string? Status { get; set; }
        public int? RentalId { get; set; }
        public int? MonthsUnpaid { get; set; }
        public string? IncreaseAnchorDate { get; set; }
        public int? IncreaseFrequencyMonths { get; set; }
        public bool IsSixMonthPromotion { get; set; }
        public decimal? PlannedPaymentAmount { get; set; }
        public bool HasPlannedPayment { get; set; }
    }

    public class SyncPaymentMethodDto
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Commission { get; set; }
    }

    public class SyncRentalDto
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public bool Active { get; set; }
    }

    public class SyncSnapshotDto
    {
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
        public List<SyncClientDto> Clients { get; set; } = new();
        public List<SyncPaymentMethodDto> PaymentMethods { get; set; } = new();
        public List<SyncRentalDto> Rentals { get; set; } = new();
    }

    /// <summary>
    /// A single queued payment to be synced from an offline client.
    /// Maps 1-to-1 with the existing CreatePaymentTransaction DTO.
    /// </summary>
    public class OfflinePaymentDto
    {
        public string LocalId { get; set; } = string.Empty; // GUID generated by frontend for tracking
        public int ClientId { get; set; }
        public int PaymentMethodId { get; set; }
        public string MovementType { get; set; } = "CREDITO";
        public string? Concept { get; set; }
        public decimal Amount { get; set; }
        public DateTime Date { get; set; }
        public bool IsAdvancePayment { get; set; }
        public int? AdvanceMonths { get; set; }
        public decimal? CommissionAmount { get; set; }
        public string? CommissionConcept { get; set; }
        public bool SkipFutureProjection { get; set; } = true; // Offline payments skip complex projections by default
        public string? SurchargeAction { get; set; }
        public decimal? SurchargeAmount { get; set; }
        public string? ExpectedPaymentStateToken { get; set; }
    }

    public class SyncPaymentsRequestDto
    {
        public List<OfflinePaymentDto> Payments { get; set; } = new();
    }

    public class SyncPaymentResultDto
    {
        public string LocalId { get; set; } = string.Empty;
        public bool Success { get; set; }
        public string? ErrorMessage { get; set; }
    }

    public class SyncPaymentsResponseDto
    {
        public List<SyncPaymentResultDto> Results { get; set; } = new();
        public int SuccessCount => Results.Count(r => r.Success);
        public int FailureCount => Results.Count(r => !r.Success);
    }
}
